### ISSUE TITLE
License inconsistencies

### ISSUE THREAD

**Issue by psakar** [jboss/jboss-jaxrs-api_spec#3]
LICENSE file specifies CDDL 1.0 license
pom.xml specifies additional license GNU General Public License, Version 2 with the Classpath Exception
Can you please either add GPL 2.0 with Classpath Exception to LICENSE file or remove it from pom.xml ?

**Comment by asoldano** [comment]
I believe this issue is stale, both pom.xml in master and LICENSE file currently include CDDL 1.0 *and* GPL 2.0 w/ Classpath Exception.
